# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Npm Install'

- task: Npm@1
  inputs:
    command: publish
    customRegistry: useNpmrc
    publishRegistry: useFeed
    publishFeed: 'Piri.Npm'
  displayName: 'Publish to Feed'